# Generated by Django 5.2.12 on 2026-04-15 13:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_user_passage_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('endDate', models.DateField()),
                ('postDate', models.DateField(auto_now_add=True)),
                ('startDate', models.DateField()),
                ('status', models.IntegerField(choices=[(1, 'A fazer'), (2, 'Em andamento'), (3, 'Concluído')], max_length=1)),
                ('notification', models.BooleanField(default=False)),
                ('user', models.ManyToManyField(related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
            },
        ),
    ]
