# Generated by Django 5.2.12 on 2026-04-08 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
    ]
