# Generated by Django 5.2.12 on 2026-04-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ManyToManyField(related_name='tasks', to='core.category'),
        ),
    ]
