# Generated by Django 5.2.12 on 2026-06-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_gang_user_gang'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='matricula',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
