# Generated by Django 5.2.12 on 2026-06-02 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_user_matricula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='matricula',
            new_name='matriculation',
        ),
    ]
