# Generated by Django 5.2.12 on 2026-06-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_matricula_user_matriculation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='matriculation',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
