# Generated by Django 5.2.12 on 2026-06-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_link_alter_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='name',
            field=models.CharField(blank=True, default=models.URLField(), max_length=100, null=True),
        ),
    ]
