# Generated by Django 5.2.12 on 2026-07-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_link_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='country',
            field=models.ManyToManyField(related_name='link_country', to='core.country'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='country',
            field=models.ManyToManyField(related_name='schedule_country', to='core.country'),
        ),
    ]
