# Generated by Django 5.2.12 on 2026-08-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_link_country_schedule_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='docs',
            field=models.ManyToManyField(blank=True, related_name='schedule_docs', to='core.link'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='category',
            field=models.IntegerField(choices=[(1, 'Postagem'), (2, 'Debate'), (3, 'Mesa de cooperação'), (4, 'Apresentação cultural')]),
        ),
    ]
