# Generated by Django 5.2.12 on 2026-08-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_schedule_docs_alter_schedule_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(1, 'Dança Típica'), (2, 'Comida Típica')], null=True),
        ),
    ]
