# Generated by Django 5.2.12 on 2026-09-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_schedule_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='docs',
            field=models.ManyToManyField(blank=True, related_name='schedule', to='core.link'),
        ),
    ]
