# Generated by Django 5.2.12 on 2026-09-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_schedule_docs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='docs',
            field=models.ManyToManyField(blank=True, related_name='schedules', to='core.link'),
        ),
    ]
